global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'xhuma'
    static_configs:
      - targets: ['xhuma:80']
    metrics_path: '/metrics'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8890']

  # OpenTelemetry Collector Metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8890']

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
