[project]
name = "Xhuma"
version = "0.9"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.138",
    "pyjwt>=2.13.0",
    "httpx",
    "xmltodict",
    "uvicorn[standard]",
    "fhirclient~=3.0.0",
    "redis",
    "cryptography>=48.0.1",
    "jwcrypto",
    "pydantic",
    "opentelemetry-api",
    "opentelemetry-sdk",
    "opentelemetry-exporter-otlp-proto-grpc",
    "opentelemetry-instrumentation-fastapi",
    "opentelemetry-instrumentation-asgi",
    "opentelemetry-instrumentation-httpx",
    "opentelemetry-instrumentation-logging",
    "opentelemetry-instrumentation-redis",
    "asyncpg",
    "sqlalchemy",
    "grpcio",
    "python-multipart>=0.0.31",
    "sqlmodel",
    "alembic",
    "psycopg[binary]",
    "azure-monitor-opentelemetry>=1.8.7",
]

[tool.isort]
profile = "black"

[dependency-groups]
dev = [
    "black",
    "websockets",
    "isort",
    "pytest",
    "xmlschema",
    "pytest-asyncio",
    "pytest-benchmark",
    "flake8",
    "pre-commit",
    "coverage",
    "ruff>=0.15.12",
    "locust",
    "azure-identity",
    "azure-keyvault-secrets",
]

[tool.uv]
package = false
default-groups = "all"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.python.org/simple"

[tool.creosote]
paths=[
    "app",
    "alembic"]
deps-file="pyproject.toml"
sections=["project.dependencies"]
