"""add audit tables

Revision ID: bcc2e8eaade2
Revises:
Create Date: 2026-02-10 10:21:54.603522

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcc2e8eaade2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("organisation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_role_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_role_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_org_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("purpose_of_use", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subject_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("client_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        op.f("ix_audit_event_action"), "audit_event", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_event_time"), "audit_event", ["event_time"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_organisation"),
        "audit_event",
        ["organisation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_event_outcome"), "audit_event", ["outcome"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_request_id"), "audit_event", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_sequence"), "audit_event", ["sequence"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_subject_ref"), "audit_event", ["subject_ref"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_trace_id"), "audit_event", ["trace_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_user_id"), "audit_event", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_event_user_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_trace_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_subject_ref"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_sequence"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_request_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_outcome"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_organisation"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_event_time"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_action"), table_name="audit_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
