name: Deploy to Azure with Terraform

# This workflow will only run when:
# 1. A PR to the play branch is merged
# 2. It's manually triggered via the Actions tab

on:
  pull_request:
    types: [closed]
    branches: [ play ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'rg-xhuma-play'
        type: choice
        options:
          - rg-xhuma-play
          - dev
          - test
          - prod

jobs:
  terraform:
    # Only run when PR is merged, not when it's closed without merging
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'rg-xhuma-play' }}  # Use the selected environment for secrets
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set environment variables
      id: env-vars
      run: |
        echo "ENVIRONMENT=${{ github.event.inputs.environment || 'rg-xhuma-play' }}" >> $GITHUB_ENV
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Select Azure subscription
      run: |
        az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
    
    - name: Terraform Init
      run: |
        cd azure/terraform
        terraform init
    
    # For first deployment, we'll skip the import step
    # The import-resources.sh script can be used manually if needed
    
    - name: Terraform Validate
      run: |
        cd azure/terraform
        terraform validate
    
    - name: Terraform Plan
      run: |
        cd azure/terraform
        terraform plan \
          -var="environment=${{ env.ENVIRONMENT }}" \
          -var="redis_password=${{ secrets.REDIS_PASSWORD }}" \
          -var="postgres_password=${{ secrets.POSTGRES_PASSWORD }}" \
          -var="api_key=${{ secrets.API_KEY }}" \
          -var="grafana_admin_password=${{ secrets.GRAFANA_ADMIN_PASSWORD }}" \
          -out=tfplan
    
    - name: Terraform Apply
      run: |
        cd azure/terraform
        terraform apply -auto-approve tfplan
      
    - name: Get ACR Credentials
      id: acr-creds
      run: |
        cd azure/terraform
        # Extract environment name without prefixes
        ENV_NAME=$(echo "${{ env.ENVIRONMENT }}" | sed -E 's/^rg-xhuma-//g' | sed -E 's/^rg-//g')
        
        # Get ACR details
        ACR_NAME="crxhuma${ENV_NAME}"
        ACR_LOGIN_SERVER=$(az acr show --name $ACR_NAME --resource-group ${{ env.ENVIRONMENT }} --query loginServer -o tsv)
        
        # Set outputs
        echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV
        
        # If ACR_USERNAME and ACR_PASSWORD are not set in GitHub secrets, get them from Azure
        if [[ -z "${{ secrets.ACR_USERNAME }}" || -z "${{ secrets.ACR_PASSWORD }}" ]]; then
          echo "ACR credentials not found in GitHub secrets, retrieving from Azure..."
          ACR_CREDS=$(az acr credential show --name $ACR_NAME --resource-group ${{ env.ENVIRONMENT }})
          ACR_USERNAME=$(echo $ACR_CREDS | jq -r '.username')
          ACR_PASSWORD=$(echo $ACR_CREDS | jq -r '.passwords[0].value')
          
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV
          echo "Retrieved ACR credentials from Azure"
        else
          echo "Using ACR credentials from GitHub secrets"
        fi
  
  build-and-push:
    needs: terraform
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'rg-xhuma-play' }}  # Use the selected environment for secrets
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME || env.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD || env.ACR_PASSWORD }}
    
    - name: Build and push Xhuma image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.ACR_LOGIN_SERVER }}/xhuma:${{ github.sha }},${{ env.ACR_LOGIN_SERVER }}/xhuma:latest
